v0.2.1 changes
protolambda/mergemock pull request #22
Opened 2022-04-19 12:41 UTC by metachris

* Updates relay implementation to conform with spec v0.2.1
* Supersedes #20

2022-04-19 12:57 UTC, metachris commented on consensus.go
> -	if c.builder != nil && attributes != nil {
Removed because the builder API no longer supports `forkChoiceUpdated`

2022-04-30 09:39 UTC, lightclient requested changes
Missing SSZ of the types and BLS support.

2022-04-30 09:39 UTC, lightclient commented on api/builder.go
> +	"github.com/flashbots/mev-boost/types"
Please remove this dependency. We should redefine all the types in `mergemock`. This let's us release new versions without waiting on upstream components.

2022-04-30 09:39 UTC, lightclient commented on api/builder.go
> +func BuilderGetHeader(ctx context.Context, cl *rpc.Client, log logrus.Ext1FieldLogger, blockHash common.Hash) (*types.ExecutionPayloadHeaderV1, error) {
This should be extended to take `slot` and `pubkey`.

2022-04-30 09:39 UTC, lightclient commented on api/builder.go
> +	return &result.Message.Header, nil
Should return either `message` and `signature` or it should verify `message` against `signature` and return `message` if successful.

2022-04-30 09:39 UTC, lightclient commented on api/builder.go
> +func BuilderGetPayload(ctx context.Context, cl *rpc.Client, log logrus.Ext1FieldLogger, header *types.ExecutionPayloadHeaderV1) (*ExecutionPayloadV1, error) {
This takes a `BlindedBeaconBlock` and a `signature`.

2022-04-30 09:39 UTC, lightclient commented on relay.go
> +	return &res, nil
This functions needs to correctly register the validator, including verifying the signature.

2022-04-30 09:39 UTC, lightclient commented on relay.go
> +func (r *RelayBackend) GetPayloadV1(ctx context.Context, block types.BlindedBeaconBlockV1, signature hexutil.Bytes) (*ExecutionPayloadV1, error) {
Should only reveal if the block is correctly signed.

2022-05-11 11:03 UTC, closed without merging